version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_DOCKER_PORT}:6379"
    networks:
      - net

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "${POSTGRES_DBNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_USER}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./scripts/sql/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_DOCKER_PORT}:5432"
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - postgres
    networks:
      - net

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge